- color: 0366d6
  description: Pull requests that update a dependency file
  name: dependencies
- color: 0075ca
  description: Improvements or additions to documentation
  name: documentation
- color: cfd3d7
  description: This issue or pull request already exists
  name: duplicate
- color: 7057ff
  description: Good for newcomers
  name: good first issue
- color: 008672
  description: Extra attention is needed
  name: help wanted
- color: e4e669
  description: This doesn't seem right
  name: invalid
- color: 50e087
  name: new rule
- color: d876e3
  description: Further information is requested
  name: question
- color: f78ff0
  name: waiting for release
- color: ffffff
  description: This will not be worked on
  name: wontfix
